import { ActivityGrade, StudentGroup } from '../types';

export type OfficialRosterEntry = {
  name: string;
  email: string;
  group: StudentGroup;
  grade: ActivityGrade;
  active: boolean;
};

export const OFFICIAL_STUDENT_ROSTER: OfficialRosterEntry[] = [
  { name: "ANGEL SIERRA, ELISA", email: "elisa713.angel@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "BALCAZAR ORTA, JACOBO", email: "jacobo419.balcazar@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "BRAVO GIRALDO, VICENTE", email: "vicente871.bravo@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "CADAVID CARDENAS, MAXIMILIANO", email: "maximiliano689.cadavid@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "DE VIVERO MARIN, MARIA JOSE", email: "maria973.devivero@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "DEVIA RIVERA, LUCIANA", email: "luciana798.devia@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "FERNANDEZ PABON, JOAQUIN", email: "joaquin840.fernandez@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "GALLON LOPEZ, PEDRO", email: "pedro179.gallon@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "GONZALEZ TONDREAU, TOMAS IGNACIO", email: "tomas458.gonzalez@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "LALINDE SILVA, TOMAS", email: "tomas916.lalinde@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "MARULANDA VILLEGAS, DAMIAN", email: "damian916.marulanda@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "MELO RICHARD, LEONOR", email: "leonor202.melo@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "MENESES RIVERA, JUAN DAVID", email: "juan369.meneses@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "OQUENDO WALKER, AGUSTIN", email: "agustin880.oquendo@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "PELLEGRINI, ISABELLA", email: "isabella855.pellegrini@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "PEREZ BUITRAGO, JULIANA", email: "juliana710.perez@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "RAMIREZ ARANZAZU, ALICIA", email: "alicia618.ramirez@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "RESTREPO ARANGO, SARA", email: "sara507.restrepo@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "RESTREPO VELASQUEZ, JERONIMO", email: "jeronimo035.restrepo@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "RIVERA CIFUENTES, RAFAEL", email: "rafael084.rivera@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "SEGURA SALDARRIAGA, ANTONIA", email: "antonia079.segura@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "TOBON PINEDA, JULIETA", email: "julieta898.tobon@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "TRUJILLO ORTEGA, VICTORIA", email: "victoria282.trujillo@s.montessori.edu.co", group: "4A", grade: "4", active: true },
  { name: "CALLE MUÑOZ, MARIANA", email: "mariana940.calle@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "CASTRO AGUIRRE, MILAGROS", email: "milagros997.castro@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "CORDOBA VALERO, MAXIMILIANO", email: "maximiliano814.cordoba@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "GARCIA ISAZA, MATIAS", email: "matias304.garcia@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "GAVIRIA DIAZ, ANA LUCIA", email: "ana620.gaviria@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "GIRALDO GIRALDO, AGUSTIN", email: "agustin658.giraldo@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "LOPEZ ANGEL, EMILIO", email: "emilio410.lopez@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "LOPEZ DUQUE, MARIA", email: "maria056.lopez@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "LOPEZ SAENZ, EUGENIA", email: "eugenia733.lopez@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "MARULANDA VILLEGAS, ABIGAIL", email: "abigail917.marulanda@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "MEDINA SIERRA, GUADALUPE", email: "guadalupe566.medina@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "MONTOYA CHAMORRO, MAXIMILIANO", email: "maximiliano481.montoya@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "MUÑOZ RESTREPO, PABLO", email: "pablo215.munoz@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "OCHOA GARCES, MARIA JOSE", email: "maria578.ochoa@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "OSSMA HERNANDEZ, ALEJANDRO", email: "alejandro597.ossma@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "PALACIO ISAZA, HELENA", email: "helena552.palacio@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "QUEVEDO TRUJILLO, VALERIA", email: "valeria941.quevedo@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "RAMIREZ CARDENAS, MARTINA", email: "martina681.ramirez@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "RESTREPO MARIN, DANIEL", email: "daniel800.restrepo@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "RODRIGUEZ ALCOCER, VICENTE", email: "vicente146.rodriguez@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "RUEDA PALMA, VICTORIA SOFIA", email: "victoria567.rueda@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "TORO GRANADOS, ANTONELLA", email: "antonella344.toro@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "TORRES DUQUE, AGUSTIN", email: "agustin190.torres@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "ZAPATA ZABALA, MARIA DE LOS ANGELES", email: "maria168.zapata@s.montessori.edu.co", group: "4B", grade: "4", active: true },
  { name: "ARBOLEDA MOLINA, MARIA", email: "maria674.arboleda@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "BETANCUR HERNANDEZ, MARIA ANTONIA", email: "maria962.betancur@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "BOUTIN, SOPHIA VICTORIA", email: "sophia819.boutin@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "CABARCAS URIBE, ELISA", email: "elisa985.cabarcas@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "CASTAÑO MAYA, CLARA", email: "clara019.castano@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "ESCOBAR RENDON, DAVID", email: "david901.escobar@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "FRANCO RESTREPO, EMILIANO", email: "emiliano145.franco@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "FRANCO SIERRA, PASCUAL", email: "pascual741.franco@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "GIRALDO BELTRAN, VICTORIA", email: "victoria617.giraldo@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "GOMEZ GOMEZ, ANTONIA", email: "antonia195.gomez@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "GONZALEZ TONDREAU, MARIA GRACIA", email: "maria253.gonzalez@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "HUAZA GUTIERREZ, OLIVIA", email: "olivia586.huaza@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "MAGRINI ZULUAGA, MIA", email: "mia954.magrini@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "MEJIA CALLE, AGUSTIN", email: "agustin382.mejia@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "MONTOYA GALEANO, MARTINA", email: "martina234.montoya@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "OSPINO CABRALES, MATEO", email: "mateo004.ospino@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "PENAGOS MEJIA, ANA MARIA", email: "ana849.penagos@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "PEREZ BUITRAGO, SUSANA", email: "susana709.perez@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "RAMIREZ LOPEZ, ALICIA", email: "alicia104.ramirez@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "RESTREPO MARIN, SAMUEL", email: "samuel799.restrepo@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "SIERRA VILLA, MATIAS", email: "matias865.sierra@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "VALLEJO MONTOYA, AGUSTIN", email: "agustin910.vallejo@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "ZAPATA BETANCUR, MATIAS", email: "matias921.zapata@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "ZUÑIGA PALACIO, ELENA", email: "elena622.zuniga@s.montessori.edu.co", group: "4C", grade: "4", active: true },
  { name: "AGUIRRE CORREA, SANTIAGO", email: "santiago978.aguirre@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "ARBELAEZ MUÑOZ, ISAAC", email: "isaac755.arbelaez@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "ARRIOLA VALERO, GUADALUPE", email: "guadalupe739.arriola@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "BOTERO ARDILA, MARIA", email: "maria742.botero@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "CASTRO MOLINA, LUCIA", email: "lucia338.castro@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "CORRALES SANCHEZ, MONTSERRAT", email: "montserrat546.corrales@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "CORREA PINTO, MARTIN", email: "martin334.correa@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "FAJARDO CALDERON, SANTIAGO", email: "santiago211.fajardo@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "GOMEZ ESCOBAR, LUCIA", email: "lucia762.gomez@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "IGUARAN VARGAS, RAFAEL JAIME", email: "rafael709.iguaran@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "LEON ATEHORTUA, MARTINA", email: "martina671.leon@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "MANTILLA ESCOBAR, EMILIO", email: "emilio759.mantilla@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "MAYORCA GONZALEZ, DASHA", email: "dasha607.mayorca@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "MEJIA JARAMILLO, SIMON", email: "simon499.mejia@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "OROZCO GONZALEZ, FEDERICO", email: "federico181.orozco@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "PEREZ ECHAVARRIA, MARIA DEL MAR", email: "maria744.perez@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "POSADA ASTAIZA, JERONIMO", email: "jeronimo985.posada@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "PRAOLINI ARCILA, ANTONELLA", email: "antonella061.praolini@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "RESTREPO GONZALEZ, ELENA", email: "elena349.restrepo@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "TAMAYO ALMONACID, JACOBO", email: "jacobo453.tamayo@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "VALENCIA GOMEZ, LUCIANA", email: "luciana002.valencia@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "VALENCIA SIERRA, ANTONIO", email: "antonio900.valencia@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "VELEZ VELASQUEZ, ANTONIO", email: "antonio923.velez@s.montessori.edu.co", group: "5A", grade: "5", active: true },
  { name: "AGUDELO SIERRA, CLEMENTE", email: "clemente859.agudelo@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "ALZATE BUENO, TOMAS", email: "tomas458.alzate@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "ARANGO ROJAS, LUCAS", email: "lucas117.arango@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "CORREA ARISTIZABAL, EMILIA", email: "emilia882.correa@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "ESCOBAR PARRA, LUCIANA", email: "luciana344.escobar@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "GARCIA GIRALDO, SALOMON", email: "salomon458.garcia@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "GODOY NAVARRO, FELIPE", email: "felipe120.godoy@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "GUTIERREZ OYUELA, MARIA DEL MAR", email: "maria800.gutierrez@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "HIGUERA RAMIREZ, JUAN MARTIN", email: "juan083.higuera@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "HINESTROZA ARISTIZABAL, EMILIA", email: "emilia680.hinestroza@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "MONCADA RAMIREZ, LUCIANA", email: "luciana860.moncada@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "MORALES DAVALOS, CRISTOBAL LEON", email: "cristobal873.morales@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "NAVARRO TRUJILLO, SUSANA", email: "susana418.navarro@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "OROZCO BOTERO, PEDRO", email: "pedro813.orozco@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "PEREZ ARANGO, MARTINA", email: "martina421.perez@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "PINEDA ARCHILA, NICOLAS", email: "nicolas775.pineda@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "PINZON JARAMILLO, MATIAS", email: "matias521.pinzon@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "RESTREPO BALLEN, SABINA", email: "sabina824.restrepo@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "RODRIGUEZ LAZIDOU, ISABELLA", email: "isabella474.rodriguez@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "ROLDAN ECHEVERRI, MARTINA", email: "martina486.roldan@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "STEARMAN, SARA LUCIA", email: "sara006.stearman@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "TELLEZ RESTREPO, PABLO", email: "pablo868.tellez@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "VARGAS MARIN, VALENTINA", email: "valentina971.vargas@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "VELEZ MORENO, PEDRO", email: "pedro059.velez@s.montessori.edu.co", group: "5B", grade: "5", active: true },
  { name: "ARBELAEZ VALENCIA, MILAGROS", email: "milagros733.arbelaez@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "BARRENECHE HOYOS, SANTIAGO", email: "santiago885.barreneche@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "CORDOBA VALERO, LUCIANO", email: "luciano815.cordoba@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "ESCOBAR OCHOA, SARA", email: "sara816.escobar@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "GALLEGO PALACIO, ISABELA", email: "isabela119.gallego@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "GALVEZ CORTES, SARA", email: "sara934.galvez@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "IBARRA NOREÑA, ALICIA", email: "alicia881.ibarra@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "JARAMILLO CASTRO, EMILIANA", email: "emiliana906.jaramillo@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "MENDOZA ECHEVERRY, LORENZO", email: "lorenzo737.mendoza@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "MESA ANGEL, ALICIA", email: "alicia031.mesa@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "MESA CARDONA, MIGUEL", email: "miguel432.mesa@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "MONTOYA VELASQUEZ, EMILIANA", email: "emiliana721.montoya@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "MUÑOZ MONTOYA, JUAN JOSE", email: "juan691.munoz@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "NAVARRO TRUJILLO, ALEJANDRO", email: "alejandro417.navarro@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "OQUENDO WALKER, MARTIN", email: "martin864.oquendo@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "PALACIO FIGUEROA, MARTIN", email: "martin967.palacio@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "PINEDO PINEDA, NICOLAS", email: "nicolas730.pinedo@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "RAMIREZ ARANGO, ISABELLA", email: "isabella065.ramirez@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "RESTREPO HURTADO, EMILIO", email: "emilio855.restrepo@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "RESTREPO MATALLANA, ELISA", email: "elisa438.restrepo@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "SOSA AGUDELO, LUCAS", email: "lucas736.sosa@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "TOBON PARRA, ANTONIA", email: "antonia161.tobon@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "VILLEGAS ACOSTA, MIGUEL", email: "miguel281.villegas@s.montessori.edu.co", group: "5C", grade: "5", active: true },
  { name: "VILLEGAS GOMEZ, MIGUEL", email: "miguel388.villegas@s.montessori.edu.co", group: "5C", grade: "5", active: true },
];
